baseURL = 'https://xxr0ss.github.io/'
languageCode = 'zh-cn'
title = 'XX の Blog'
theme = 'PaperMod'
publishDir = "docs"

[params]
    [params.homeInfoParams]
        title = "Hi there"
        Content = "信息安全 | 逆向"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2